set lin 500
set ver off
col OWNER format a10 wrap
col CONSTRAINT_NAME format a30 wrap
col TABLE_NAME format a20 wrap
col SEARCH_CONDITION format a30 wrap
col R_OWNER format a10 wrap
col R_CONSTRAINT_NAME format a30 wrap
col INDEX_OWNER format a10 wrap
col INDEX_NAME format a20 wrap
undefine table_name
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION, R_OWNER, R_CONSTRAINT_NAME, INDEX_OWNER, INDEX_NAME FROM ALL_CONSTRAINTS A WHERE CONSTRAINT_NAME IN (SELECT c.CONSTRAINT_NAME FROM ALL_CONS_COLUMNS c WHERE TABLE_NAME LIKE UPPER('&table_name'));
