SET TERMOUT OFF
SET FEEDBACK OFF

COL X NEW_VALUE X NOPRINT
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') || '@' || SYS_CONTEXT('USERENV', 'DB_NAME') X from dual;

SET SQLP '&X> '

ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS'; 
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD-MON-YYYY HH24:MI:SS.FF'; 

SET TERMOUT ON
SET FEEDBACK ON
SET LINESIZE 100
SET TAB OFF
SET TRIM ON
SET TRIMSPOOL ON
