set lin 32767
set ver off
col OWNER format a20 wrap
col DATA_TYPE format a10 wrap
col DATA_DEFAULT format a20 wrap
undefine table_name
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, DEFAULT_LENGTH, DATA_DEFAULT FROM ALL_TAB_COLS WHERE TABLE_NAME LIKE UPPER('&table_name');
